# -*- coding: utf-8 -*-
"""Canonical Quest3TriggerUI payload build.

Rewrites `namespace Quest3TriggerUI` to `namespace Quest3TriggerUI.v<tag>`
in every payload source so each build's component types have globally
unique full names. Unity binds MonoBehaviour script classes by full name,
so a unique name per build is what makes hot reload actually run new code
instead of silently re-instantiating the first-loaded assembly's class.

Also emits VersionedShim.cs: a legacy-name bridge component that spawns
the versioned plugin, so a still-running old loader does not fail/spam
when it polls a transformed payload.

Usage:
  python build_payload.py [--tag vTAG] [--loader] [--out DIR]
"""
import argparse, datetime, hashlib, os, re, subprocess, sys

ROOT = r"F:\vam1.22.0.12"
SRC = os.path.join(ROOT, u"工作区", u"Quest3TriggerUI工程", "plugin_sources")
CSC = r"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
MANAGED = os.path.join(ROOT, "VaM_Data", "Managed")
BEPINEX = os.path.join(ROOT, "BepInEx", "core")

REFS = [
    (MANAGED, "mscorlib.dll"), (MANAGED, "Assembly-CSharp.dll"),
    (MANAGED, "UnityEngine.dll"), (MANAGED, "UnityEngine.CoreModule.dll"),
    (MANAGED, "UnityEngine.UI.dll"), (MANAGED, "UnityEngine.UIModule.dll"),
    (MANAGED, "UnityEngine.TextRenderingModule.dll"),
    (MANAGED, "UnityEngine.AudioModule.dll"),
    (MANAGED, "Bass.Net.dll"),
    (MANAGED, "UnityEngine.AssetBundleModule.dll"),
    (BEPINEX, "BepInEx.dll"), (BEPINEX, "0Harmony.dll"),
    (MANAGED, "System.dll"), (MANAGED, "System.Core.dll"),
    (MANAGED, "System.Drawing.dll"),
    (MANAGED, "UnityEngine.ImageConversionModule.dll"),
    (MANAGED, "UnityEngine.IMGUIModule.dll"),
    (MANAGED, "UnityEngine.InputModule.dll"),
    (MANAGED, "UnityEngine.VRModule.dll"),
    (MANAGED, "UnityEngine.PhysicsModule.dll"),
]

EXCLUDE = re.compile(r"(Tests\.cs$|\.source\.cs$|^HotUpdateLoader\.cs$)", re.I)
MEMORY_LIST = os.path.join(SRC, os.pardir, "memory_modules.txt")


def memory_sources():
    if not os.path.exists(MEMORY_LIST):
        return set()
    with open(MEMORY_LIST, encoding="utf-8") as stream:
        return {line.strip() for line in stream if line.strip() and not line.startswith("#")}

# `namespace Quest3TriggerUI` declarations (flat namespace in every file).
NS_DECL = re.compile(r"(namespace\s+)Quest3TriggerUI(?=\s|{|;)")
# Qualified references Quest3TriggerUI.SomeType — uppercase after the dot.
# Lowercase matches (file names, harmony ids, config paths) stay untouched.
QUAL_REF = re.compile(r"Quest3TriggerUI(?=\.[A-Z])")

SHIM = u"""// Auto-generated by build_payload.py — do not edit.
// Legacy-name bridge for loaders that still resolve the fixed
// Quest3TriggerUI.Quest3TriggerUIPlugin name. It must stay alive after
// spawning the versioned plugin: a v1.0 loader treats a self-destroying
// component as a failed load and retries forever, spawning an unbounded
// fleet of versioned runtimes. The v1.1+ loader prefers the versioned
// type and never instantiates this shim.
namespace Quest3TriggerUI
{
    public class Quest3TriggerUIPlugin : UnityEngine.MonoBehaviour
    {
        public static bool RuntimeReady = true;

        private void Awake()
        {
            // Spawn the newest versioned runtime in the AppDomain. Scanning
            // (instead of a compile-time typeof) keeps this correct even when
            // Unity substitutes an older same-name shim class on AddComponent.
            try
            {
                System.Type best = null;
                foreach (var asm in
                    System.AppDomain.CurrentDomain.GetAssemblies())
                {
                    System.Type[] ts;
                    try { ts = asm.GetTypes(); }
                    catch { continue; }
                    for (int i = 0; i < ts.Length; i++)
                    {
                        System.Type t = ts[i];
                        if (t == null || t.Name != "Quest3TriggerUIPlugin" ||
                            t.Namespace == null ||
                            !t.Namespace.StartsWith("Quest3TriggerUI.v") ||
                            !typeof(UnityEngine.MonoBehaviour)
                                .IsAssignableFrom(t))
                            continue;
                        if (best == null || string.CompareOrdinal(
                            t.FullName, best.FullName) > 0)
                            best = t;
                    }
                }
                if (best != null) gameObject.AddComponent(best);
            }
            catch (System.Exception) { }
        }
    }
}
"""


def read_text(path):
    raw = open(path, "rb").read()
    for enc in ("utf-8-sig", "utf-8", "gbk"):
        try:
            return raw.decode(enc), raw.startswith(b"\xef\xbb\xbf")
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", "replace"), False


def transform(text, tag):
    text = NS_DECL.sub(lambda m: m.group(1) + "Quest3TriggerUI." + tag, text)
    text = QUAL_REF.sub("Quest3TriggerUI." + tag, text)
    return text


def run_csc(rsp_path):
    proc = subprocess.Popen([CSC, "/noconfig", "@" + rsp_path],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    out = proc.communicate()[0].decode("mbcs", "replace")
    sys.stdout.write(out)
    return proc.returncode


def write_rsp(path, out_dll, sources):
    lines = [u"/nologo", u'/out:"%s"' % out_dll, u"/noconfig",
             u"/target:library", u"/optimize+", u"/nostdlib+", u"/unsafe+"]
    for d, f in REFS:
        lines.append(u'/reference:"%s"' % os.path.join(d, f))
    lines.extend(u'"%s"' % s for s in sources)
    open(path, "wb").write(u"\r\n".join(lines).encode("utf-8"))


def build_payload(tag, out_dir):
    work = os.path.join(out_dir, "src_" + tag)
    if not os.path.isdir(work):
        os.makedirs(work)
    sources = []
    memory = memory_sources()
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(".cs") or EXCLUDE.search(name):
            continue
        if name in memory:
            continue
        src = os.path.join(SRC, name)
        text, had_bom = read_text(src)
        new = transform(text, tag)
        dst = os.path.join(work, name)
        # Always emit a BOM: csc falls back to the system codepage without
        # one, which would corrupt CJK literals in UTF-8 sources.
        open(dst, "wb").write(b"\xef\xbb\xbf" + new.encode("utf-8"))
        sources.append(dst)
    shim = os.path.join(work, "VersionedShim.cs")
    open(shim, "wb").write(b"\xef\xbb\xbf" +
                           SHIM.replace("@TAG@", tag).encode("utf-8"))
    sources.append(shim)
    out_dll = os.path.join(out_dir, "Quest3TriggerUI_payload_" + tag + ".dll")
    rsp = os.path.join(out_dir, "build_" + tag + ".rsp")
    write_rsp(rsp, out_dll, sources)
    if run_csc(rsp) != 0:
        sys.exit("payload build failed")
    return out_dll


def build_loader(out_dir):
    out_dll = os.path.join(out_dir, "Quest3TriggerUI.HotLoader.dll")
    rsp = os.path.join(out_dir, "build_loader.rsp")
    write_rsp(rsp, out_dll, [os.path.join(SRC, "HotUpdateLoader.cs")])
    if run_csc(rsp) != 0:
        sys.exit("loader build failed")
    return out_dll


def sha256(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest().upper()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="v" + datetime.datetime.now()
                    .strftime("%m%d%H%M%S"))
    ap.add_argument("--loader", action="store_true")
    ap.add_argument("--out", default=os.path.join(SRC, os.pardir,
                    "build_out"))
    args = ap.parse_args()
    out_dir = os.path.abspath(args.out)
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    dll = build_payload(args.tag, out_dir)
    print("[build] payload %s sha=%s" % (dll, sha256(dll)))
    if args.loader:
        ldll = build_loader(out_dir)
        print("[build] loader  %s sha=%s" % (ldll, sha256(ldll)))


if __name__ == "__main__":
    main()
