using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Reflection;
using System.Threading;
using BepInEx;
using SimpleJSON;
using UnityEngine;

namespace Quest3TriggerUI
{
    // Self-contained pinyin input engine — the VR-side Chinese IME.
    //
    // Why not the desktop IME? We tried bridging IMM32: composition text is
    // exposed to legacy apps through CUAS, but modern TSF IMEs (Microsoft
    // Pinyin) never populate ImmGetCandidateList for unaware apps — the
    // candidate data simply isn't readable. Routing letters through
    // keybd_event also breaks whenever the desktop window isn't foreground.
    // A built-in engine has neither dependency and behaves identically
    // regardless of which IME the desktop happens to use.
    //
    // Data files (generated by 工作区2/PinyinEngine/build_dict.py from
    // rime-pinyin-simp + phrase-pinyin-data + rime-terra-pinyin):
    //   pinyin_dict.txt      letters<TAB>word word ...   (exact keys)
    //   pinyin_initials.txt  initials<TAB>word word ...  (简拼 shorthand)
    //   pinyin_fuzzy.txt     normletters<TAB>word ...    (模糊音 keys)
    //   pinyin_syllables.txt syllable per line           (segmentation set)
    internal static class PinyinEngine
    {
        internal enum KeyResult { NotHandled, Consumed, CommitText }

        private const int PageSize = 9;
        private const int MaxCandidates = 400;
        private const int MaxSegPaths = 64;
        private const int MaxInputLen = 40;

        private static bool _enabled = true;
        private static string _comp = string.Empty;
        private static int _pageStart;
        private static int _nextSeq;
        private static readonly List<Cand> _cands = new List<Cand>();
        private static readonly ImeCandidateSnapshot _snapshot =
            new ImeCandidateSnapshot();

        // Cloud-first candidate tier — Baidu search-suggestion API, queried on
        // a background thread per composition change. It maps pinyin (full or
        // 简拼) to the words people actually search — modern terms like
        // 雷电将军 land first. Cloud words insert at the top of the local
        // candidate list; on failure (offline, timeout, empty result) the
        // engine backs off for CloudCooldownMs and the local dictionary
        // carries the session alone.
        internal static bool CloudEnabled = true;
        private const int CloudTimeoutMs = 2000;
        private const int CloudCooldownMs = 15000;
        private const int CloudMinLetters = 3;
        private const int CloudMaxInFlight = 3;
        private static string _cloudLastQuery;
        private static int _cloudInFlight;
        private static int _cloudDownUntil;      // Environment.TickCount
        private static bool _cloudFailLogged;
        private static bool _cloudTlsReady;
        private static readonly object _cloudGate = new object();
        private static readonly Queue<CloudResult> _cloudDone =
            new Queue<CloudResult>();

        private sealed class CloudResult
        {
            internal string Query;                 // raw letters queried
            internal string[] Words;               // ranked candidates
            internal int[] Consumed;               // letters covered per word
        }

        private static Dictionary<string, string[]> _full;
        private static Dictionary<string, string[]> _initials;
        private static Dictionary<string, string[]> _fuzzy;
        private static HashSet<string> _syllables;
        private static string[] _allKeys;

        // ---- user dictionary (learning) -----------------------------------
        // Committed words are remembered under both their full-syllable key
        // and their initials key, so a phrase typed once in full pinyin is
        // later reachable via 简拼 too. Persisted to a small txt next to the
        // dictionaries; writes are coalesced on a background thread.
        internal static bool UserLearning = true;
        private const string UserFileName = "Quest3TriggerUI.pinyin-user.txt";
        private const int MaxUserPerKey = 12;
        private static Dictionary<string, List<UEntry>> _userFull;
        private static Dictionary<string, List<UEntry>> _userInit;
        private static bool _userDirty;
        private static bool _userSaveQueued;
        // Accumulates the syllables+text of consecutive commits within one
        // composition — when the composition empties, the whole phrase is
        // learned as a unit (桌面输入法的组词记忆).
        private static readonly List<string> _sessionSyls =
            new List<string>();
        private static readonly System.Text.StringBuilder _sessionText =
            new System.Text.StringBuilder();

        private sealed class UEntry
        {
            internal string Word;
            internal int Count;
            internal string InitKey;   // "" for single-syllable words
        }
        private static bool _loadStarted;

        private sealed class Cand
        {
            internal string Word;
            internal int Consume;   // raw letters this word covers
            internal int Rank;      // -2 cloud,0 exact-full,1 fuzzy-full,2 completion,3 exact-partial,4 fuzzy-partial,5 initials
            internal int Cover;     // syllables/letters covered — tiebreak inside a rank
            internal int Seq;       // insertion order = weight order within bucket
        }

        private sealed class Seg
        {
            internal readonly List<string> Syls = new List<string>();
            internal string Partial = string.Empty;
        }

        internal static bool Available
        {
            get { return EnsureLoaded(); }
        }

        // The VR-side 中/英 flag — independent of the desktop IME entirely.
        internal static bool Enabled
        {
            get { return _enabled && EnsureLoaded(); }
        }

        internal static ImeCandidateSnapshot Snapshot
        {
            get { return _snapshot; }
        }

        internal static void Toggle()
        {
            _enabled = !_enabled;
            ResetComp();
            Log("toggle -> " + (_enabled ? "中文" : "英文"));
        }

        internal static void Reset()
        {
            ResetComp();
        }

        private static void Log(string message)
        {
            if (Quest3TriggerUIPlugin.Log != null)
                Quest3TriggerUIPlugin.Log.LogInfo("Q3 pinyin " + message);
        }

        // ---- dictionary ---------------------------------------------------

        // The dictionary is ~48MB / 1.6M keys — parsing on the caller thread
        // would freeze VR for seconds on first input focus. Kick a background
        // load at plugin init instead; _full's non-null is the ready flag.
        internal static bool EnsureLoaded()
        {
            if (_full != null) return true;
            if (_loadStarted) return false;
            _loadStarted = true;
            ThreadPool.QueueUserWorkItem(delegate { LoadWorker(); });
            return false;
        }

        private static void LoadWorker()
        {
            try
            {
                string dir = PluginDir();
                var full = LoadTable(Path.Combine(dir, "pinyin_dict.txt"));
                var initials = LoadTable(Path.Combine(dir, "pinyin_initials.txt"));
                var fuzzy = LoadTable(Path.Combine(dir, "pinyin_fuzzy.txt"));
                var syllables = LoadSyllables(Path.Combine(dir, "pinyin_syllables.txt"));
                string[] keys = null;
                if (full != null)
                {
                    keys = new string[full.Count];
                    full.Keys.CopyTo(keys, 0);
                    Array.Sort(keys, StringComparer.Ordinal);
                }
                var ufull = new Dictionary<string, List<UEntry>>();
                var uinit = new Dictionary<string, List<UEntry>>();
                LoadUserDict(UserDictPath(), ufull, uinit);
                _userFull = ufull;
                _userInit = uinit;
                _initials = initials;
                _fuzzy = fuzzy;
                _syllables = syllables;
                _allKeys = keys;
                Thread.MemoryBarrier();
                _full = full;   // assign last — its non-null marks load complete
                Log("loaded full=" + (_full == null ? 0 : _full.Count) +
                    " init=" + (_initials == null ? 0 : _initials.Count) +
                    " fuzzy=" + (_fuzzy == null ? 0 : _fuzzy.Count) +
                    " syl=" + (_syllables == null ? 0 : _syllables.Count) +
                    " dir=" + dir);
            }
            catch (Exception e)
            {
                if (Quest3TriggerUIPlugin.Log != null)
                    Quest3TriggerUIPlugin.Log.LogError("Q3 pinyin load: " + e);
            }
        }

        private static string PluginDir()
        {
            try
            {
                string location = Assembly.GetExecutingAssembly().Location;
                if (!string.IsNullOrEmpty(location))
                {
                    string dir = Path.GetDirectoryName(location);
                    if (File.Exists(Path.Combine(dir, "pinyin_dict.txt")))
                        return dir;
                }
            }
            catch { }
            return Path.Combine(Paths.PluginPath, "Quest3TriggerUI");
        }

        private static Dictionary<string, string[]> LoadTable(string path)
        {
            if (!File.Exists(path)) return null;
            Dictionary<string, string[]> table =
                new Dictionary<string, string[]>(65536);
            foreach (string line in File.ReadAllLines(path))
            {
                int tab = line.IndexOf('\t');
                if (tab <= 0) continue;
                string key = line.Substring(0, tab);
                string[] words = line.Substring(tab + 1)
                    .Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                if (words.Length > 0) table[key] = words;
            }
            return table;
        }

        private static HashSet<string> LoadSyllables(string path)
        {
            if (!File.Exists(path)) return null;
            HashSet<string> set = new HashSet<string>();
            foreach (string line in File.ReadAllLines(path))
            {
                string s = line.Trim();
                if (s.Length > 0) set.Add(s);
            }
            return set;
        }

        // User data lives in BepInEx/config like the other plugin state
        // files — it survives payload updates and migrates with cfg.
        private static string UserDictPath()
        {
            try
            {
                return Path.Combine(Paths.ConfigPath, UserFileName);
            }
            catch
            {
                return Path.Combine(PluginDir(), UserFileName);
            }
        }

        // File format: fullKey<TAB>initKey<TAB>word<TAB>count
        private static void LoadUserDict(string path,
            Dictionary<string, List<UEntry>> ufull,
            Dictionary<string, List<UEntry>> uinit)
        {
            try
            {
                if (!File.Exists(path)) return;
                foreach (string line in File.ReadAllLines(path))
                {
                    string[] p = line.Split('\t');
                    if (p.Length < 4 || p[0].Length == 0) continue;
                    int count;
                    if (!int.TryParse(p[3], out count) || count <= 0)
                        count = 1;
                    UEntry e = new UEntry {
                        Word = p[2], Count = count, InitKey = p[1] };
                    AddRef(ufull, p[0], e);
                    if (p[1].Length > 0)
                        AddRef(uinit, p[1], e);
                }
            }
            catch (Exception e)
            {
                if (Quest3TriggerUIPlugin.Log != null)
                    Quest3TriggerUIPlugin.Log.LogError(
                        "Q3 pinyin userdict load: " + e.Message);
            }
        }

        private static UEntry AddUser(
            Dictionary<string, List<UEntry>> table, string key, string word)
        {
            List<UEntry> list;
            if (!table.TryGetValue(key, out list))
            {
                list = new List<UEntry>();
                table[key] = list;
            }
            for (int i = 0; i < list.Count; i++)
            {
                if (list[i].Word == word)
                {
                    list[i].Count++;
                    // Bubble up — most-used floats to the top of the key.
                    while (i > 0 && list[i - 1].Count < list[i].Count)
                    {
                        UEntry t = list[i - 1];
                        list[i - 1] = list[i];
                        list[--i] = t;
                    }
                    return list[i];
                }
            }
            UEntry e2 = new UEntry { Word = word, Count = 1, InitKey = "" };
            list.Add(e2);
            if (list.Count > MaxUserPerKey)
                list.RemoveRange(MaxUserPerKey, list.Count - MaxUserPerKey);
            return e2;
        }

        private static void AddRef(
            Dictionary<string, List<UEntry>> table, string key, UEntry e)
        {
            List<UEntry> list;
            if (!table.TryGetValue(key, out list))
            {
                list = new List<UEntry>();
                table[key] = list;
            }
            for (int i = 0; i < list.Count; i++)
                if (list[i].Word == e.Word) { list[i] = e; return; }
            list.Add(e);
        }

        private static void Learn(List<string> syls, string word)
        {
            if (!UserLearning || syls == null || syls.Count == 0 ||
                string.IsNullOrEmpty(word) || word.Length > 24)
                return;
            bool cjk = false;
            for (int i = 0; i < word.Length; i++)
                if (word[i] >= 0x4E00 && word[i] <= 0x9FFF)
                { cjk = true; break; }
            if (!cjk) return;   // latin commits aren't vocabulary
            if (_userFull == null)
            {
                _userFull = new Dictionary<string, List<UEntry>>();
                _userInit = new Dictionary<string, List<UEntry>>();
            }
            string full = Join(syls, syls.Count);
            lock (_userFull)   // SaveUserDict enumerates on a bg thread
            {
                UEntry e = AddUser(_userFull, full, word);
                if (syls.Count >= 2 && _userInit != null)
                {
                    System.Text.StringBuilder sb =
                        new System.Text.StringBuilder(syls.Count);
                    for (int i = 0; i < syls.Count; i++)
                        sb.Append(syls[i][0]);
                    e.InitKey = sb.ToString();
                    AddRef(_userInit, e.InitKey, e);
                }
            }
            _userDirty = true;
            if (!_userSaveQueued)
            {
                _userSaveQueued = true;
                ThreadPool.QueueUserWorkItem(delegate
                {
                    try
                    {
                        Thread.Sleep(1500);   // coalesce rapid commits
                        SaveUserDict();
                    }
                    catch { }
                    finally { _userSaveQueued = false; }
                });
            }
        }

        private static void SaveUserDict()
        {
            if (!_userDirty || _userFull == null) return;
            _userDirty = false;
            try
            {
                System.Text.StringBuilder sb =
                    new System.Text.StringBuilder(4096);
                lock (_userFull)
                {
                    foreach (KeyValuePair<string, List<UEntry>> kv in
                        _userFull)
                    {
                        List<UEntry> list = kv.Value;
                        for (int i = 0; i < list.Count; i++)
                        {
                            UEntry e = list[i];
                            sb.Append(kv.Key).Append('\t')
                              .Append(e.InitKey).Append('\t')
                              .Append(e.Word).Append('\t')
                              .Append(e.Count).Append('\n');
                        }
                    }
                }
                File.WriteAllText(UserDictPath(), sb.ToString());
            }
            catch (Exception e)
            {
                if (Quest3TriggerUIPlugin.Log != null)
                    Quest3TriggerUIPlugin.Log.LogError(
                        "Q3 pinyin userdict save: " + e.Message);
            }
        }

        // Called on plugin shutdown so the tail of a typing session isn't
        // lost to the 1.5s debounce window.
        internal static void FlushUserDict()
        {
            SaveUserDict();
        }

        // ---- key handling -------------------------------------------------

        internal static KeyResult HandleKey(ushort key, bool shift, out string commit)
        {
            commit = null;
            bool hasComp = _comp.Length > 0;

            // Letters feed the composition — both when empty (starts it) and
            // mid-composition.
            if (key >= 0x41 && key <= 0x5A)
            {
                if (_comp.Length >= MaxInputLen) return KeyResult.Consumed;
                _comp += (char)(key + 0x20);
                RebuildCandidates();
                return KeyResult.Consumed;
            }

            // Apostrophe = explicit syllable separator (xi'an style).
            if (key == 0xDE && hasComp && !shift)
            {
                _comp += '\'';
                RebuildCandidates();
                return KeyResult.Consumed;
            }

            // Digit keys select candidates while composing; with no comp they
            // fall through and type the digit literally.
            if (key >= 0x31 && key <= 0x39)
            {
                if (!hasComp) return KeyResult.NotHandled;
                int absolute = _pageStart + (key - 0x31);
                if (absolute < _cands.Count)
                {
                    CommitCand(_cands[absolute], out commit);
                    return KeyResult.CommitText;
                }
                return KeyResult.Consumed;
            }
            if (key == 0x30 && hasComp)
                return KeyResult.Consumed; // 0 is not a selection key

            if (key == 0x08)
            {
                if (!hasComp) return KeyResult.NotHandled;
                _comp = _comp.Substring(0, _comp.Length - 1);
                RebuildCandidates();
                return KeyResult.Consumed;
            }
            if (key == 0x1B)
            {
                if (!hasComp) return KeyResult.NotHandled;
                ResetComp();
                return KeyResult.Consumed;
            }
            if (key == 0x0D)
            {
                if (!hasComp) return KeyResult.NotHandled;
                // Enter commits the raw letters — desktop convention.
                commit = _comp.Replace("'", string.Empty);
                ResetComp();
                return KeyResult.CommitText;
            }
            if (key == 0x20)
            {
                if (!hasComp) return KeyResult.NotHandled;
                if (_cands.Count > 0)
                {
                    Cand top = _cands[Math.Min(_pageStart, _cands.Count - 1)];
                    CommitCand(top, out commit);
                    return KeyResult.CommitText;
                }
                return KeyResult.Consumed;
            }
            // PageUp/PageDown and -/= page the candidate list while composing.
            if (hasComp && (key == 0x21 || key == 0x22 || key == 0xBD || key == 0xBB))
            {
                Page(key == 0x22 || key == 0xBB);
                return KeyResult.Consumed;
            }
            // Punctuation while composing commits the highlighted candidate
            // first, then inserts the punctuation — same as a desktop IME.
            if (hasComp && IsPunctKey(key))
            {
                char punct = VrTextInputBridge.Character(key, shift, false);
                if (punct == '\0') return KeyResult.Consumed;
                if (_cands.Count > 0)
                {
                    Cand top = _cands[Math.Min(_pageStart, _cands.Count - 1)];
                    string word = top.Word;
                    LearnCand(top);
                    Consume(top.Consume);
                    commit = word + punct;
                }
                else
                {
                    commit = _comp.Replace("'", string.Empty) + punct;
                    ResetComp();
                }
                return KeyResult.CommitText;
            }
            return KeyResult.NotHandled;
        }

        private static bool IsPunctKey(ushort key)
        {
            return (key >= 0xBA && key <= 0xC0) ||
                   (key >= 0xDB && key <= 0xDE);
        }

        // ---- candidates ---------------------------------------------------

        internal static void CommitAt(int absoluteIndex, out string commit)
        {
            commit = null;
            if (absoluteIndex < 0 || absoluteIndex >= _cands.Count) return;
            CommitCand(_cands[absoluteIndex], out commit);
        }

        // Commits a candidate: learn the word (and the accumulated phrase
        // when this finishes the composition), then consume its letters.
        private static void CommitCand(Cand c, out string commit)
        {
            commit = c.Word;
            LearnCand(c);
            Consume(c.Consume);
        }

        private static void LearnCand(Cand c)
        {
            // Syllables covering the consumed prefix of the composition —
            // Enumerate returns fullest coverage first.
            string prefix = RawPrefix(c.Consume);
            List<Seg> segs = Enumerate(prefix.Replace("'", string.Empty));
            List<string> syls = segs.Count > 0 ? segs[0].Syls : null;
            if (syls == null || syls.Count == 0)
            {
                _sessionSyls.Clear();
                _sessionText.Length = 0;
                return;
            }
            Learn(syls, c.Word);
            _sessionSyls.AddRange(syls);
            _sessionText.Append(c.Word);
            int rawLeft = 0;
            for (int i = 0; i < _comp.Length; i++)
                if (_comp[i] != '\'') rawLeft++;
            if (c.Consume < rawLeft) return;   // composition continues
            // Composition finished — learn the accumulated multi-word
            // phrase as one entry so it recalls as a unit next time.
            if (_sessionText.Length > c.Word.Length)
                Learn(new List<string>(_sessionSyls), _sessionText.ToString());
            _sessionSyls.Clear();
            _sessionText.Length = 0;
        }

        // First `letters` non-apostrophe characters of the composition.
        private static string RawPrefix(int letters)
        {
            int skipped = 0, i = 0;
            for (; i < _comp.Length && skipped < letters; i++)
                if (_comp[i] != '\'') skipped++;
            return _comp.Substring(0, i);
        }

        // A commit may cover only the first few syllables of the composition
        // (partial candidates) — strip exactly that many letters and keep the
        // rest composing, like a desktop IME's word-by-word sentence input.
        private static void Consume(int letters)
        {
            if (letters >= _comp.Replace("'", string.Empty).Length)
            {
                ResetComp();
                return;
            }
            int skipped = 0, i = 0;
            for (; i < _comp.Length && skipped < letters; i++)
            {
                if (_comp[i] != '\'') skipped++;
            }
            while (i < _comp.Length && _comp[i] == '\'') i++;
            _comp = _comp.Substring(i);
            _pageStart = 0;
            RebuildCandidates();
        }

        internal static void Page(bool next)
        {
            _pageStart += next ? PageSize : -PageSize;
            if (_pageStart < 0) _pageStart = 0;
            if (_cands.Count > 0 && _pageStart >= _cands.Count)
                _pageStart = ((_cands.Count - 1) / PageSize) * PageSize;
            RefreshSnapshot();
        }

        private static void ResetComp()
        {
            _comp = string.Empty;
            _pageStart = 0;
            _cands.Clear();
            _sessionSyls.Clear();
            _sessionText.Length = 0;
            RefreshSnapshot();
        }

        // Candidate tiers, best first:
        //   0 exact    — word covers the first k syllables (longest first)
        //   1 fuzzy    — same but through the 模糊音 normalized table
        //   2 complete — dictionary key extends the whole input (词组联想)
        //   3 initials — 简拼 shorthand on the whole input
        private static void RebuildCandidates()
        {
            _cands.Clear();
            _pageStart = 0;
            string raw = _comp.Replace("'", string.Empty);
            if (raw.Length == 0 || _full == null)
            {
                RefreshSnapshot();
                return;
            }

            List<Seg> segs = Enumerate(raw);
            _nextSeq = 0;
            HashSet<string> seen = new HashSet<string>();
            // Learned words first — user frequency outranks dictionary
            // weight, like a desktop IME's 词频记忆. Rank -1 sits below
            // cloud (-2) and above exact (0).
            if (UserLearning && _userFull != null)
            {
                for (int s = 0; s < segs.Count; s++)
                {
                    Seg seg = segs[s];
                    for (int k = seg.Syls.Count; k >= 1; k--)
                        EmitUser(_userFull, Join(seg.Syls, k),
                            RawLen(seg.Syls, k), 1000 + k, seen,
                            ref _nextSeq);
                }
                if (_userInit != null)
                    EmitUser(_userInit, raw, raw.Length, 1000,
                        seen, ref _nextSeq);
                // Prefix recall: a learned phrase surfaces as soon as the
                // input prefixes its full or initials key — no need to type
                // the whole thing (桌面输入法的记忆联想). User dict is
                // small, so a linear key scan per keystroke is fine.
                // Cover stays low so exact user hits still sort above.
                if (raw.Length >= 2)
                {
                    int recalled = 0;
                    foreach (string ukey in _userFull.Keys)
                    {
                        if (recalled >= 40) break;
                        if (ukey.Length > raw.Length &&
                            ukey.StartsWith(raw) &&
                            EmitUser(_userFull, ukey, raw.Length, 0,
                                seen, ref _nextSeq))
                            recalled++;
                    }
                    if (_userInit != null)
                    {
                        foreach (string ukey in _userInit.Keys)
                        {
                            if (recalled >= 40) break;
                            if (ukey.Length > raw.Length &&
                                ukey.StartsWith(raw) &&
                                EmitUser(_userInit, ukey, raw.Length, 0,
                                    seen, ref _nextSeq))
                                recalled++;
                        }
                    }
                }
            }
            int maxK = 0;
            for (int i = 0; i < segs.Count; i++)
                if (segs[i].Syls.Count > maxK) maxK = segs[i].Syls.Count;
            for (int k = maxK; k >= 1 && _cands.Count < MaxCandidates; k--)
            {
                for (int s = 0; s < segs.Count; s++)
                {
                    Seg seg = segs[s];
                    if (seg.Syls.Count < k) continue;
                    bool whole = k == seg.Syls.Count && seg.Partial.Length == 0;
                    int consume = RawLen(seg.Syls, k);
                    Emit(_full, Join(seg.Syls, k), consume,
                        whole ? 0 : 3, k, seen, ref _nextSeq);
                    if (_fuzzy != null)
                        Emit(_fuzzy, JoinNorm(seg.Syls, k), consume,
                            whole ? 1 : 4, k, seen, ref _nextSeq);
                }
            }
            // Completion: dictionary keys that extend the whole raw input —
            // this is what surfaces long phrases as soon as they diverge.
            // _allKeys is ordinally sorted, so binary-search the range start
            // and walk only the prefix-matching run (~1.6M-key safe).
            int completions = 0;
            if (_allKeys != null)
            {
                int lo = Array.BinarySearch(_allKeys, raw, StringComparer.Ordinal);
                if (lo < 0) lo = ~lo;
                for (int i = lo; i < _allKeys.Length && completions < 200; i++)
                {
                    string key = _allKeys[i];
                    if (!key.StartsWith(raw)) break;
                    // Only completions within ~2 syllables ahead are useful —
                    // corpus long-tail keys (nihaiaita…) would otherwise eat
                    // the cap before real short keys like nihao get a turn.
                    if (key.Length <= raw.Length || key.Length > raw.Length + 6)
                        continue;
                    if (Emit(_full, key, raw.Length, 2, 1000 - key.Length, seen, ref _nextSeq))
                        completions++;
                }
            }
            // 简拼 last.
            if (_initials != null)
                Emit(_initials, raw, raw.Length, 5, raw.Length, seen, ref _nextSeq);

            _cands.Sort(CompareCands);
            if (_cands.Count > MaxCandidates)
                _cands.RemoveRange(MaxCandidates, _cands.Count - MaxCandidates);
            RefreshSnapshot();
            QueryCloud(raw);
        }

        private static readonly Comparison<Cand> CompareCands =
            delegate(Cand a, Cand b)
            {
                int d = a.Rank - b.Rank;
                if (d != 0) return d;
                d = b.Cover - a.Cover;
                if (d != 0) return d;
                return a.Seq - b.Seq;
            };

        private static bool Emit(Dictionary<string, string[]> table, string key,
            int consume, int rank, int cover, HashSet<string> seen, ref int seq)
        {
            string[] words;
            if (key.Length == 0 || !table.TryGetValue(key, out words))
                return false;
            for (int i = 0; i < words.Length && _cands.Count < MaxCandidates; i++)
            {
                if (!seen.Add(words[i])) continue;
                _cands.Add(new Cand {
                    Word = words[i], Consume = consume, Rank = rank,
                    Cover = cover, Seq = seq++ });
            }
            return true;
        }

        private static bool EmitUser(
            Dictionary<string, List<UEntry>> table, string key,
            int consume, int cover, HashSet<string> seen, ref int seq)
        {
            List<UEntry> entries;
            if (key.Length == 0 || !table.TryGetValue(key, out entries))
                return false;
            for (int i = 0; i < entries.Count &&
                    _cands.Count < MaxCandidates; i++)
            {
                if (!seen.Add(entries[i].Word)) continue;
                _cands.Add(new Cand {
                    Word = entries[i].Word, Consume = consume, Rank = -1,
                    Cover = cover + entries[i].Count, Seq = seq++ });
            }
            return true;
        }

        // Enumerate every way the raw letters split into known syllables.
        // Each path may end with a "partial" tail (letters not yet a full
        // syllable) so prefix coverage still works mid-syllable.
        private static List<Seg> Enumerate(string raw)
        {
            List<Seg> output = new List<Seg>();
            if (_syllables == null || raw.Length == 0) return output;
            Walk(raw, 0, new List<string>(), output);
            // Prefer the fullest-coverage path first for display; among equal
            // coverage prefer FEWER syllables (ni'hao over ni'ha'o).
            output.Sort(delegate(Seg a, Seg b) {
                int ca = 0, cb = 0;
                for (int i = 0; i < a.Syls.Count; i++) ca += a.Syls[i].Length;
                for (int i = 0; i < b.Syls.Count; i++) cb += b.Syls[i].Length;
                int d = cb - ca;
                return d != 0 ? d : a.Syls.Count - b.Syls.Count;
            });
            return output;
        }

        private static void Walk(string raw, int pos, List<string> syls, List<Seg> output)
        {
            if (output.Count >= MaxSegPaths) return;
            while (pos < raw.Length && raw[pos] == '\'') pos++;
            if (pos >= raw.Length)
            {
                Seg done = new Seg();
                done.Syls.AddRange(syls);
                output.Add(done);
                return;
            }
            // Close-out option: the remaining tail is an unfinished syllable.
            Seg partial = new Seg();
            partial.Syls.AddRange(syls);
            partial.Partial = raw.Substring(pos);
            output.Add(partial);
            // Extend by each syllable that matches at pos (longest first).
            for (int len = Math.Min(6, raw.Length - pos); len >= 1; len--)
            {
                string s = raw.Substring(pos, len);
                if (s.IndexOf('\'') >= 0) break;
                if (!_syllables.Contains(s)) continue;
                syls.Add(s);
                Walk(raw, pos + len, syls, output);
                syls.RemoveAt(syls.Count - 1);
                if (output.Count >= MaxSegPaths) return;
            }
        }

        private static string Join(List<string> syls, int count)
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            for (int i = 0; i < count; i++) sb.Append(syls[i]);
            return sb.ToString();
        }

        private static string JoinNorm(List<string> syls, int count)
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            for (int i = 0; i < count; i++) sb.Append(NormSyl(syls[i]));
            return sb.ToString();
        }

        private static int RawLen(List<string> syls, int count)
        {
            int n = 0;
            for (int i = 0; i < count; i++) n += syls[i].Length;
            return n;
        }

        // Fuzzy normalization — mirrors build_dict.py fuzzy_syl exactly.
        private static string NormSyl(string s)
        {
            if (s.StartsWith("zh")) s = "z" + s.Substring(2);
            else if (s.StartsWith("ch")) s = "c" + s.Substring(2);
            else if (s.StartsWith("sh")) s = "s" + s.Substring(2);
            else if (s.Length > 1 && s.StartsWith("n")) s = "l" + s.Substring(1);
            else if (s.Length > 1 && s.StartsWith("f")) s = "h" + s.Substring(1);
            if (s.EndsWith("iang")) s = s.Substring(0, s.Length - 4) + "ian";
            else if (s.EndsWith("uang")) s = s.Substring(0, s.Length - 4) + "uan";
            else if (s.EndsWith("ang")) s = s.Substring(0, s.Length - 3) + "an";
            else if (s.EndsWith("eng")) s = s.Substring(0, s.Length - 3) + "en";
            else if (s.EndsWith("ing")) s = s.Substring(0, s.Length - 3) + "in";
            return s;
        }

        // ---- cloud candidates --------------------------------------------

        // Drain finished queries on the main thread. Stale responses (the
        // composition moved past the queried letters) are dropped.
        internal static void Tick()
        {
            CloudResult result = null;
            lock (_cloudGate)
            {
                if (_cloudDone.Count > 0) result = _cloudDone.Dequeue();
            }
            if (result == null) return;
            string raw = _comp.Replace("'", string.Empty);
            if (result.Query != raw) return;      // stale — typing moved on
            MergeCloud(result);
        }

        private static void QueryCloud(string raw)
        {
            if (!CloudEnabled || raw.Length < CloudMinLetters ||
                raw == _cloudLastQuery) return;
            if (Environment.TickCount < _cloudDownUntil) return;
            lock (_cloudGate)
            {
                if (_cloudInFlight >= CloudMaxInFlight) return;
                _cloudInFlight++;
            }
            _cloudLastQuery = raw;
            if (!_cloudTlsReady)
            {
                _cloudTlsReady = true;
                try { ServicePointManager.SecurityProtocol |= (SecurityProtocolType)3072; }
                catch { }
            }
            ThreadPool.QueueUserWorkItem(delegate { FetchCloud(raw); });
        }

        private static void FetchCloud(string raw)
        {
            CloudResult result = null;
            try
            {
                string url = "https://suggestion.baidu.com/su?wd=" +
                    Uri.EscapeDataString(raw) + "&ie=utf-8&json=1";
                HttpWebRequest req = (HttpWebRequest)WebRequest.Create(url);
                req.Timeout = CloudTimeoutMs;
                req.ReadWriteTimeout = CloudTimeoutMs;
                req.UserAgent = "Mozilla/5.0";
                using (WebResponse resp = req.GetResponse())
                using (Stream stream = resp.GetResponseStream())
                using (StreamReader reader = new StreamReader(stream, System.Text.Encoding.UTF8))
                {
                    result = ParseCloud(reader.ReadToEnd(), raw);
                }
                lock (_cloudGate)
                {
                    _cloudInFlight--;
                    if (result != null) _cloudDone.Enqueue(result);
                    _cloudDownUntil = 0;
                    _cloudFailLogged = false;
                }
            }
            catch (Exception e)
            {
                lock (_cloudGate)
                {
                    _cloudInFlight--;
                    _cloudDownUntil = Environment.TickCount + CloudCooldownMs;
                    if (!_cloudFailLogged)
                    {
                        _cloudFailLogged = true;
                        Log("cloud down, local only for " + CloudCooldownMs / 1000 +
                            "s: " + e.GetType().Name);
                    }
                }
            }
        }

        // Response is JSONP: window.baidu.sug({"g":[{"q":"词"},...]}). Search
        // suggestions are whole-word matches — no partial coverage, so every
        // candidate consumes all input. Mixed-script SEO junk ("...TXT百度云")
        // gets filtered: pure CJK only, and length is capped since long tails
        // are search noise, not words the user is typing.
        private static CloudResult ParseCloud(string text, string raw)
        {
            int open = text.IndexOf('(');
            int close = text.LastIndexOf(')');
            if (open < 0 || close <= open) return null;
            JSONNode root = JSONNode.Parse(text.Substring(open + 1, close - open - 1));
            JSONArray items = root["g"].AsArray;
            if (items == null || items.Count == 0) return null;
            int cap = Math.Max(8, raw.Length / 2);
            List<string> words = new List<string>(items.Count);
            for (int i = 0; i < items.Count && words.Count < MaxCandidates; i++)
            {
                string q = items[i]["q"].Value;
                if (string.IsNullOrEmpty(q) || q.Length > cap) continue;
                if (!IsPureCjk(q)) continue;
                if (!words.Contains(q)) words.Add(q);
            }
            if (words.Count == 0) return null;
            CloudResult result = new CloudResult();
            result.Query = raw;
            result.Words = words.ToArray();
            result.Consumed = new int[words.Count];
            for (int i = 0; i < result.Consumed.Length; i++)
                result.Consumed[i] = raw.Length;
            return result;
        }

        private static bool IsPureCjk(string s)
        {
            for (int i = 0; i < s.Length; i++)
            {
                char c = s[i];
                bool cjk = (c >= 0x4E00 && c <= 0x9FFF) || c == 0xB7;
                if (!cjk) return false;
            }
            return s.Length > 0;
        }

        // Cloud words insert at the top of the list (rank -2) like a real
        // IME's 云候选 slot; local dictionary candidates stay below, with
        // duplicates removed so the cloud ordering governs.
        private static void MergeCloud(CloudResult result)
        {
            string raw = _comp.Replace("'", string.Empty);
            HashSet<string> cloudWords = new HashSet<string>();
            for (int i = 0; i < result.Words.Length; i++)
            {
                if (!string.IsNullOrEmpty(result.Words[i]))
                    cloudWords.Add(result.Words[i]);
            }
            for (int i = _cands.Count - 1; i >= 0; i--)
                if (cloudWords.Contains(_cands[i].Word)) _cands.RemoveAt(i);
            for (int i = 0; i < result.Words.Length && _cands.Count < MaxCandidates; i++)
            {
                string word = result.Words[i];
                if (string.IsNullOrEmpty(word)) continue;
                int consume = Math.Min(result.Consumed[i], raw.Length);
                if (consume <= 0) consume = raw.Length;
                _cands.Add(new Cand {
                    Word = word,
                    Consume = consume,
                    Rank = -2,
                    Cover = consume,
                    Seq = _nextSeq++ });
            }
            _cands.Sort(CompareCands);
            if (_cands.Count > MaxCandidates)
                _cands.RemoveRange(MaxCandidates, _cands.Count - MaxCandidates);
            if (_pageStart >= _cands.Count)
                _pageStart = _cands.Count > 0
                    ? ((_cands.Count - 1) / PageSize) * PageSize : 0;
            RefreshSnapshot();
        }

        private static void RefreshSnapshot()
        {
            _snapshot.Composition = DisplayComp();
            _snapshot.Candidates.Clear();
            for (int i = 0; i < _cands.Count; i++)
                _snapshot.Candidates.Add(_cands[i].Word);
            _snapshot.PageStart = _pageStart;
            _snapshot.PageSize = PageSize;
            _snapshot.Selection = _cands.Count > 0
                ? Math.Min(_pageStart, _cands.Count - 1)
                : 0;
            _snapshot.ChineseMode = _enabled;
        }

        // Display like a desktop IME: syllables apostrophe-separated, the
        // unfinished tail appended raw ("ni'hao" / "zhong'hua'renm").
        private static string DisplayComp()
        {
            if (_comp.Length == 0) return string.Empty;
            if (_syllables == null) return _comp;
            string raw = _comp.Replace("'", string.Empty);
            List<Seg> segs = Enumerate(raw);
            if (segs.Count == 0) return _comp;
            Seg best = segs[0];
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            for (int i = 0; i < best.Syls.Count; i++)
            {
                if (i > 0) sb.Append('\'');
                sb.Append(best.Syls[i]);
            }
            if (best.Partial.Length > 0)
            {
                if (sb.Length > 0) sb.Append('\'');
                sb.Append(best.Partial);
            }
            return sb.ToString();
        }
    }
}
